---
title: Puzzelkamer
hero_image: images/banner.png
description: Maak een ruimteschip puzzelkamer met een personage dat puzzels oplost.
version: 4
listed: true
copyedit: true
last_tested: '2021-03-26'
steps:
  - 
    title: Je gaat maken
  - 
    title: Wie zit er in de puzzelkamer?
  - 
    title: De knop puzzel
    completion:
      - gekoppeld
  - 
    title: De wiel puzzel
  - 
    title: De asteroïden puzzel
    completion:
      - intern
  - 
    title: Snelle quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - extern
  - 
    title: Verbeter je project
  - 
    title: Wat kun je verder nog doen?
