---
title: Puzzle room
hero_image: images/banner.png
description: Create a spaceship puzzle room with a character that solves puzzles.
version: 4
listed: true
copyedit: true
last_tested: '2021-03-26'
steps:
  - title: You will make
  - title: Who's in the puzzle room?
  - title: The button puzzle
    completion:
      - engaged
  - title: The handwheel puzzle
  - title: The asteroids puzzle
    completion:
      - internal
  - title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Upgrade your project
  - title: What next?
