title: puzzle-room
hero_image: images/banner.png
description: puzzle-room description
version: 4
listed: false
copyedit: false
last_tested: "2021-05-14"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
