---
title: Ystafell posau
hero_image: images/banner.png
description: Creu ystafell posau llong ofod gyda chymeriad sy'n datrys posau.
meta_title: Scratch coding projects for kids and teens | Puzzle room
meta_description: Learn Scratch with the Raspberry Pi Foundation's coding projects for kids and teens. Create an escape room in Scratch with a character that solves puzzles.
version: 4
listed: true
copyedit: true
last_tested: '2021-03-26'
steps:
  - 
    title: Byddi di'n creu
  - 
    title: Pwy sydd yn yr ystafell posau?
  - 
    title: Pos y botwm
    completion:
      - engaged
  - 
    title: Pos yr olwyn law
  - 
    title: Pos yr asteroidau
    completion:
      - internal
  - 
    title: Cwis cyflym
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Uwchraddio dy brosiect
  - 
    title: Profwch eich hun
